#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail


if [ -f /tmp/in_target.d/$CACHED_CUDA_BIN_FILE_NAME ]; then
    # install CUDA toolkits
    sudo sh /tmp/in_target.d/$CACHED_CUDA_BIN_FILE_NAME --silent --driver --toolkit --samples
else
    echo "Could find cuda bin file: /tmp/in_target.d/$CACHED_CUDA_BIN_FILE_NAME"
    exit 1
fi
