#!/bin/bash

# NOTE(qianbiao.ng): To install Lustre with Mellanox infiniband support,
#  Mellanox OFED should be installed before lustre.

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail
