#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# TODO(turnbig): add dependencies

if [ -f /tmp/in_target.d/$CACHED_MLNX_OFED_DRIVER_FILE_NAME ]; then
    # install Mellanox OFED driver
    sudo cp /tmp/in_target.d/$CACHED_MLNX_OFED_DRIVER_FILE_NAME /tmp/$CACHED_MLNX_OFED_DRIVER_FILE_NAME
    sudo mkdir -p /tmp/Mellanox-OFED-driver
    sudo tar -zxf /tmp/$CACHED_MLNX_OFED_DRIVER_FILE_NAME -C /tmp/Mellanox-OFED-driver

    _OFED_INSTALLATION_FOLDER="/tmp/Mellanox-OFED-driver/"$(ls /tmp/Mellanox-OFED-driver/)
    pushd $_OFED_INSTALLATION_FOLDER
        sudo ./mlnxofedinstall --force --without-fw-update
    popd

    # reload driver
    sudo /etc/init.d/openibd restart
else
    echo "Could find Mellanox OFED drive installation file: /tmp/in_target.d/$CACHED_MLNX_OFED_DRIVER_FILE_NAME"
    exit 1
fi
