#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# echo -e "blacklist nouveau\noptions nouveau modeset=0" >> /lib/modprobe.d/dist-blacklist.conf

yum install -y "kernel-devel-$(uname -r)"

if [ -f /tmp/in_target.d/$CACHED_CUDA_11_BIN_FILE_NAME ]; then
    # install CUDA toolkits
    lsmod
    sudo sh /tmp/in_target.d/$CACHED_CUDA_11_BIN_FILE_NAME --silent --driver
    sudo cat /var/log/nvidia-installer.log
else
    echo "Could find cuda bin file: /tmp/in_target.d/$CACHED_CUDA_11_BIN_FILE_NAME"
    exit 1
fi

if [ -f /tmp/in_target.d/$CACHED_CUDA_10_BIN_FILE_NAME ]; then
    # install CUDA toolkits
    sudo sh /tmp/in_target.d/$CACHED_CUDA_10_BIN_FILE_NAME --silent --toolkit
    sudo cat /tmp/cuda_install_*.log
else
    echo "Could find cuda bin file: /tmp/in_target.d/$CACHED_CUDA_10_BIN_FILE_NAME"
    exit 1
fi
