#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# echo -e "blacklist nouveau\noptions nouveau modeset=0" >> /lib/modprobe.d/dist-blacklist.conf

# NOTE(qianbiao.ng): requires same kernel in image and build-host-server
# yum install -y "kernel-devel-$(uname -r)"

if [ -f /tmp/in_target.d/$CACHED_CUDA_11_BIN_FILE_NAME ]; then
    # install CUDA toolkits
    KERNEL_PATH=$(ls /usr/src/kernels/* -d | sort -r | head -1)
    if [ -z "$KERNEL_PATH" ]; then
        ls /usr/src/kernels/
        echo "Warning: could not find any kernel source."
        exit 1
    fi

    sudo sh /tmp/in_target.d/$CACHED_CUDA_11_BIN_FILE_NAME \
        --silent --driver --kernel-source-path=${KERNEL_PATH}
    sudo cat /var/log/nvidia-installer.log
else
    echo "Could find cuda bin file: /tmp/in_target.d/$CACHED_CUDA_11_BIN_FILE_NAME"
    exit 1
fi

if [ -f /tmp/in_target.d/$CACHED_CUDA_10_BIN_FILE_NAME ]; then
    # install CUDA toolkits
    sudo sh /tmp/in_target.d/$CACHED_CUDA_10_BIN_FILE_NAME --silent --toolkit
    sudo cat /tmp/cuda_install_*.log
else
    echo "Could find cuda bin file: /tmp/in_target.d/$CACHED_CUDA_10_BIN_FILE_NAME"
    exit 1
fi
