#!/bin/bash

# currently, PCSS element only supports CentOS 7.8
if [ "$DISTRO_NAME" != "centos" -o "${DIB_RELEASE}" != 7 ]; then
    echo 'PCSS element only support CentOS 7 distribution for now.'
    exit 1
fi

# setup cache dir
PSCC_CACHE_DIR=$DIB_IMAGE_CACHE/pcss/$DISTRO_NAME/${DIB_RELEASE}
export PSCC_CACHE_DIR

CACHED_CUDA_BIN_FILE_NAME=cuda_10.0.130_410.48_linux.run
export CACHED_CUDA_BIN_FILE_NAME

CACHED_CUDA_BIN_FILE=$PSCC_CACHE_DIR/$CACHED_CUDA_BIN_FILE_NAME
export CACHED_CUDA_BIN_FILE

CACHED_CUDA_MD5SUM_FILE=$PSCC_CACHE_DIR/MD5SUM.cuda_10
export CACHED_CUDA_MD5SUM_FILE
