#!/bin/bash

# setup cuda path

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

SCRIPTDIR=$(dirname $0)


# install setup script
mkdir -p /home/tools
install -D -g root -o root -m 0755 ${SCRIPTDIR}/setup-lustre-client-ib-network.sh /home/tools/setup-lustre-client-ib-network.sh

# run setup script
# echo "sudo sh /usr/local/sbin/setup-lustre-client-ib-network" >> /etc/rc.d/rc.local
# chmod +x /etc/rc.d/rc.local
